title: Hello World! I'm Sean Hong
description: > # this means to ignore newlines until "baseurl:"
  I'm Sean Hong(홍성민), CS student from Korea. My fields of interests are programming languages,
  machine learning, and web development(very typical, I know), but is looking more 
  deeply into iOS development, Backend development with Django and DevOps. I'm very excited and thankful
  to be a part of the generation that can bring changes to the world with code.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sean Hong(홍성민) # add your name
author-img: me_profile.jpeg # add your photo
about-author: I'm a CS student from South Korea focusing my studies more into iOS and backend developement.  # add description
social-twitter: # add your Twitter handle
social-facebook: sean.hong.750 # add your Facebook handle
social-github: KKodiac # add your Github handle
social-linkedin: sean-hong-47b977170 # add your Linkedin handle
social-email: seanhong2000@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
